#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="imap"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    purge)
        if omv_config_exists ${SERVICE_XPATH}; then
            omv_config_delete ${SERVICE_XPATH}
        fi

        # Remove Maildir skel
        rm -rf /etc/skel/Maildir

        # Postfix mkconf hack (FIXME)
        cd /usr/share/openmediavault/mkconf
        rm postfix
        mv postfix.d/10notification postfix
        rmdir postfix.d
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
